---
global:
  type: unit
  category: spacing

props:
  - name: spacing-stack-xxxs
    value: 4px
    category: spacing

  - name: spacing-stack-xxs
    value: 8px
    category: spacing

  - name: spacing-stack-xs
    value: 16px
    category: spacing

  - name: spacing-stack-sm
    value: 24px
    category: spacing

  - name: spacing-stack-md
    value: 40px
    category: spacing

  - name: spacing-stack-lg
    value: 64px
    category: spacing

  - name: spacing-stack-xl
    value: 80px
    category: spacing

  - name: spacing-stack-xxl
    value: 128px
    category: spacing

  - name: spacing-stack-xxxl
    value: 200px
    category: spacing
